// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5uIx0HVQX-Ffq6qEzaSGA5qT4-jKk1dg',
    appId: '1:645241313678:web:582cead3aee62bf694acdf',
    messagingSenderId: '645241313678',
    projectId: 'chat-app-730a8',
    authDomain: 'chat-app-730a8.firebaseapp.com',
    storageBucket: 'chat-app-730a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIaBdjmuZ0puFW9Qh4oUsk19NUvFRhtvM',
    appId: '1:645241313678:android:9a4d788fdb98897594acdf',
    messagingSenderId: '645241313678',
    projectId: 'chat-app-730a8',
    storageBucket: 'chat-app-730a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD03osEagHgYoaFA8XIuOyionFDbfo_xl4',
    appId: '1:645241313678:ios:83409ecb56ed096394acdf',
    messagingSenderId: '645241313678',
    projectId: 'chat-app-730a8',
    storageBucket: 'chat-app-730a8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD03osEagHgYoaFA8XIuOyionFDbfo_xl4',
    appId: '1:645241313678:ios:fa8526a0fdfc4de594acdf',
    messagingSenderId: '645241313678',
    projectId: 'chat-app-730a8',
    storageBucket: 'chat-app-730a8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
